allez/urls.py
from django.contrib import admin
from django.urls import path, include
from graphene_django.views import GraphQLView

from .settings import DEBUG
from ui.views import LoginUser, RegisterUser

urlpatterns = [
    path('main/', include('main.urls')),
    path('accounts/login/', LoginUser.as_view(), name='login'),
    path('accounts/signup/', RegisterUser.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path("graphql", GraphQLView.as_view(graphiql=DEBUG)),
    path('', include('ui.urls')),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pool/<int:pool_id>', views.pool, name='main/pool_endpoint'),
    path('de_table/<int:table_id>', views.de_table, name='main/de_table_endpoint'),
    path('competition/<int:comp_id>', views.competition, name='main/competition_endpoint'),
    path('organisation/<int:org_id>', views.organisation, name='main/organisation_endpoint'),
    path('stage/<int:stage_id>', views.stage_router, name='main/stage_endpoint'),
    path('<int:comp_id>/<int:stage_number>.pdf', views.stage_router_pdf, name='main/stage/pdf'),
    path('<int:comp_id>/<int:stage_number>/results', views.stage_router_results, name='main/stage/results'),
    path('<int:comp_id>/<int:stage_number>/results.pdf', views.stage_router_results_pdf, name='main/stage/results/pdf')
]

ui/urls.py
from django.urls import path
from . import views
from .views import CreateOrganisation

urlpatterns = [
    path('', views.front_page, name='ui/front_page'),
    path('organisation/create', CreateOrganisation.as_view(), name='ui/organisation/create'),
    path('organisation/list', views.organisation_list, name='ui/organisation/list'),
    path('change_org/', views.change_org, name='ui/change_org'),
    path('dt/pool/<int:pool_id>', views.dt_manage_pool, name='ui/dt_manage_pool'),
    path('dt/de/<int:de_table_id>', views.dt_manage_de_table, name='ui/dt_manage_de'),
    path('<slug:org_slug>', views.organisation, name='ui/organisation/show'),
    path('<slug:org_slug>/competitions', views.list_competitions, name='ui/org/competitions'),
    path('<slug:org_slug>/competitions/create', views.create_competition, name='ui/create_competition'),
    path('<slug:org_slug>/competitions/<int:comp_id>/manage', views.manage_competition, name='ui/manage_competition'),
    path('<slug:org_slug>/competitions/<int:comp_id>/manage/check_in', views.check_in, name='ui/check_in'),
    path('<slug:org_slug>/competitions/<int:comp_id>/manage/<int:stage_id>', views.manage_stage_router, name='ui/manage_stage'),
    path('<slug:org_slug>/competitions/<int:comp_id>/manage/<int:stage_id>/ranking', views.stage_ranking, name='ui/stage_ranking')
]

main/models/stage.py
from random import sample, seed
from django.db import models
from .pool_stage import PoolStage
from .add_stage import AddStage
from .cull_stage import CullStage
from .de_stage import DeStage


class Stage(models.Model):
    POOL = 'POO'
    DE = 'DEL'
    CULL = 'CUL'
    ADD = 'ADD'
    stage_types = ((POOL, "Pool"),
                   (DE, "Direct Elimination"),
                   (CULL, "Cull"),
                   (ADD, "Add Fencers"))
    NOT_STARTED = 'STD'
    READY = 'RDY'
    STARTED = 'GO'
    FINISHED = 'FIN'
    LOCKED = 'LCK'
    states = ((NOT_STARTED, "Not Ready"),
              (READY, "Ready to Start"),
              (STARTED, "Running"),
              (FINISHED, "Finished"),
              (LOCKED, "Finished and Confirmed"))
    type = models.CharField(max_length=3, choices=stage_types)
    state = models.CharField(max_length=3, choices=states, default=NOT_STARTED)
    competition = models.ForeignKey('main.Competition', on_delete=models.CASCADE)
    number = models.IntegerField()

    def ordered_competitors(self):
        if self.type == self.POOL:
            return PoolStage.objects.get(stage=self).ordered_competitors()
        elif self.type == self.CULL:
            return CullStage.objects.get(stage=self).ordered_competitors()
        elif self.type == self.ADD:
            return AddStage.objects.get(stage=self).ordered_competitors()
        elif self.type == self.DE:
            return DeStage.objects.get(stage=self).ordered_competitors()

    def ranked_competitors(self):
        if self.type == self.POOL:
            return PoolStage.objects.get(stage=self).ranked_competitors()
        elif self.type == self.CULL:
            return CullStage.objects.get(stage=self).ranked_competitors()
        elif self.type == self.ADD:
            return AddStage.objects.get(stage=self).ranked_competitors()
        elif self.type == self.DE:
            return DeStage.objects.get(stage=self).ranked_competitors()

    def input(self, ranked=False):
        """returns a list of entries representing the input of this stage"""
        if not Stage.objects.filter(number__lt=self.number).exists():
            return []
        else:
            ranking = Stage.objects.get(competition_id=self.competition_id,
                                        number=self.number - 1).ranked_competitors()
            if ranked:
                return ranking
            else:
                seed(self.competition.id << 30 + self.id)  # Set random number generator seed for consistent results
                return [entry for group in ranking for entry in sample(group, len(group))]

    def deletable(self):
        """returns whether a stage can be deleted or not"""
        return self.state in [self.NOT_STARTED, self.READY]

    def appendable_to(self):
        """returns whether a stage can be added after this one"""
        return self.state not in [self.LOCKED, self.FINISHED] or \
            not Stage.objects.filter(competition=self.competition, number__gt=self.number)

    def save(self, *args, **kwargs):
        creating = False
        if not self.pk:
            creating = True
        super(Stage, self).save(*args, **kwargs)
        if creating:
            if self.type == Stage.POOL:
                self.poolstage_set.create()
            elif self.type == Stage.DE:
                self.destage_set.create()
            elif self.type == Stage.ADD:
                self.addstage_set.create()
            elif self.type == Stage.CULL:
                self.cullstage_set.create()

    def complete(self):
        """returns whether a stage is complete"""
        return self.state in [self.FINISHED, self.LOCKED]

    def get_concrete_type(self):
        if self.type == Stage.POOL:
            return self.poolstage_set.first()
        elif self.type == Stage.CULL:
            return self.cullstage_set.first()
        elif self.type == Stage.DE:
            return self.destage_set.first()
        elif self.type == Stage.ADD:
            return self.addstage_set.first()

    class Meta:
        unique_together = ('number', 'competition')
        get_latest_by = 'number'

    class NotCompleteError(Exception):
        def __init__(self, message):
            super().__init__(message)

ui/models.py
from django.db import models

# Create your models here.

ui/forms/competition.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import SelectDateWidget
from django.utils import timezone
from django.utils.translation import gettext as _


class CreateCompetitionForm(forms.Form):
    name = forms.CharField(label="Competition Name", max_length=200)
    date = forms.DateField(label="Date", widget=SelectDateWidget)

    def clean_date(self):
        data = self.cleaned_data['date']
        if data < timezone.now().date():
            raise ValidationError(_('Competition dates must be in the future'))
        return data

ui/forms/user.py
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UserCreationFormWithPrivacyNotice(UserCreationForm):
    privacy_consent = forms.BooleanField(
        label="""GDPR Notice HERE"""
    )

    def is_valid(self):
        return super().is_valid() and self.cleaned_data['privacy_consent']

ui/views.py
from django.shortcuts import render
from main.models import Pool


def test(request):
    context = {'pool': Pool.objects.first().poolentry_set.all()}
    return render(request, 'ui/pool_edit.html', context)

ui/views/check_in.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from rules.contrib.views import permission_required, objectgetter
from main.models import Competition, Entry


@login_required
@permission_required('main.manage_competition',
                     fn=objectgetter(Competition, attr_name='comp_id', field_name='pk'),
                     raise_exception=True)
def check_in(request, org_slug, comp_id):
    competition = get_object_or_404(Competition, pk=comp_id)
    entries = competition.entry_set.order_by('competitor__name').all()
    return render(request, 'ui/competition/check_in.html', {'competition': competition,
                                                            'entries': entries})

ui/views/competition.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from rules.contrib.views import permission_required, objectgetter
from main.models import Competition, Organisation, Stage
from ..forms.competition import CreateCompetitionForm


@login_required
@permission_required('main.create_competition', fn=objectgetter(Organisation, attr_name='org_slug', field_name='slug'))
def create_competition(request, org_slug):
    org = get_object_or_404(Organisation, slug=org_slug)
    if request.method == 'POST':
        form = CreateCompetitionForm(request.POST)
        if form.is_valid():
            comp = org.competition_set.create(name=form.cleaned_data['name'], date=form.cleaned_data['date'])

            return HttpResponseRedirect(reverse('ui/manage_competition', args=[org_slug, comp.id]))
    else:
        form = CreateCompetitionForm()

    return render(request, 'ui/competition/create.html', {'form': form})


def list_competitions(request, org_slug):
    org = get_object_or_404(Organisation, slug=org_slug)
    comps = org.competition_set.all()
    return render(request, 'ui/competition/list.html', {'competitions': comps,
                                                        'org': org})


@login_required
@permission_required('main.manage_competition',
                     fn=objectgetter(Competition, attr_name='comp_id', field_name='pk'),
                     raise_exception=True)
def manage_competition(request, org_slug, comp_id):
    competition = get_object_or_404(Competition, pk=comp_id)
    stages_objects = competition.stage_set.order_by('number').all()
    style_map = {
        Stage.STARTED: 'table-primary',
        Stage.FINISHED: 'table-success',
        Stage.LOCKED: 'table-success'
    }
    styles = list(map(lambda x: style_map.get(x.state, ''), stages_objects))
    stages = list(zip(stages_objects, styles))
    types = Stage.stage_types
    entries = competition.entry_set.all()
    return render(request, 'ui/competition/manage.html', {'competition': competition,
                                                          'stages': stages,
                                                          'types': types,
                                                          'entries': entries,
                                                          'org_slug': org_slug})

ui/views/front_page.py
from django.shortcuts import render


def front_page(request):
    return render(request, 'ui/front_page.html')

ui/views/organisation.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import CreateView

from main.models import Organisation, OrganisationMembership


@login_required
def organisation(request, org_slug):
    org = get_object_or_404(Organisation, slug=org_slug)
    full_members = org.organisationmembership_set.exclude(state=OrganisationMembership.APPLICANT)
    applicants = org.organisationmembership_set.filter(state=OrganisationMembership.APPLICANT)
    can_manage = request.user.has_perm('main.manage_organisation', org)
    return render(request, 'ui/organisation/show.html', context={'org': org,
                                                                 'full_members': full_members,
                                                                 'applicants': applicants,
                                                                 'can_manage': can_manage})


class CreateOrganisation(LoginRequiredMixin, CreateView):
    model = Organisation
    template_name = "ui/organisation/create.html"
    fields = ["name", "email", "slug"]

    def get_success_url(self):
        org = self.object
        self.request.session['org_id'] = org.id
        slug = org.slug
        return reverse('ui/org/competitions', kwargs={'org_slug': slug})

    def form_valid(self, form):
        response = super().form_valid(form)
        org = self.object
        org.organisationmembership_set.create(state=OrganisationMembership.MANAGER, user=self.request.user)
        return response


def organisation_list(request):
    orgs = Organisation.objects
    if request.user.is_active:
        user_orgs = request.user.organisationmembership_set.values_list('organisation', flat=True)
        other_orgs = orgs.exclude(pk__in=user_orgs)
        user_orgs = orgs.filter(pk__in=user_orgs)
    else:
        user_orgs = []
        other_orgs = orgs.all()
    return render(request, 'ui/organisation/list.html', context={'user_orgs': user_orgs,
                                                                 'other_orgs': other_orgs})

ui/views/stage.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils.translation import gettext as _
from rules.contrib.views import permission_required, objectgetter
from main.models import Stage
from .stages import manage_pool_stage, manage_cull_stage, manage_de_stage, manage_add_stage


@login_required
@permission_required('main.manage_competition',
                     fn=objectgetter(Stage, attr_name='stage_id', field_name='pk'),
                     raise_exception=True)
def manage_stage_router(request, org_slug, comp_id, stage_id):
    stage = get_object_or_404(Stage, pk=stage_id)
    if stage.type == Stage.POOL:
        pool_id = stage.poolstage_set.first().id
        return manage_pool_stage(request, pool_id)
    elif stage.type == Stage.CULL:
        cull_id = stage.cullstage_set.first().id
        return manage_cull_stage(request, cull_id)
    elif stage.type == Stage.DE:
        de_id = stage.destage_set.first().id
        return manage_de_stage(request, de_id)
    elif stage.type == Stage.ADD:
        add_id = stage.addstage_set.first().id
        return manage_add_stage(request, add_id)
    else:
        return HttpResponse("Not Implemented yet")


def stage_ranking(request, org_slug, comp_id, stage_id):
    stage = get_object_or_404(Stage, pk=stage_id, competition=comp_id)
    try:
        stage_rankings = stage.ranked_competitors()
    except Stage.NotCompleteError:
        return HttpResponse(_("Stage Not Finished"))
    rankings = []
    place = 1
    for rank in stage_rankings:
        for entry in rank:
            rankings.append((place, entry))
        place += len(rank)
    return render(request, 'ui/competition/ranking.html', context={'stage': stage,
                                                                   'rankings': rankings})

ui/views/test.py
from django.shortcuts import render
from main.models import Pool


def test(request):
    context = {'pool': Pool.objects.first().poolentry_set.all()}
    return render(request, 'ui/pool_edit.html', context)

ui/views/user.py
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse

from main.models import Organisation, OrganisationMembership


@login_required
def change_org(request):
    if request.method == "GET":
        user_organisations = request.user.organisationmembership_set.all()
        context = {
            'user_orgs': user_organisations,
            'orgs': Organisation.objects.values('name', 'id')
        }
        return render(request, 'ui/user/change_org.html', context)
    elif request.method == "POST":
        id = request.POST['org_id']
        org = Organisation.objects.get(id=id)
        query = OrganisationMembership.objects.filter(organisation=org, user=request.user)
        if query.exists():
            query.update(last_active=timezone.now())
            request.session['org_id'] = id
            slug = org.slug
            return JsonResponse({'success': True,
                                 'next': reverse('ui/org/competitions', kwargs={'org_slug': slug})})
        else:
            return JsonResponse({'success': False,
                                 'reason': 'User not a member of given organisation'})

ui/templates/ui/stages/add/FINISHED.html
{% extends 'ui/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Manage Add Stage' %}{% endblock %}


{% block body %}
    <a class="btn btn-primary" href="{% url 'ui/check_in' stage.competition.organisation.slug stage.competition.id %}">
        {% trans 'Open Check In' %}
    </a>
    <br>
    <h2>{% trans "Seeding after this addition currently" %}</h2>
    <table class="table" id="entry_table">
        <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Status' %}</th>
        </tr>
        {% for entry in entries %}
            <tr>
                <td>{{ entry }}</td>
                <td>{% trans entry.get_state_display %}</td>
            </tr>
        {% endfor %}
    </table>
    <br>
    <h2>{% trans "These entries will fail to be added" %}</h2>
    <table class="table" id="entry_table">
        <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Status' %}</th>
        </tr>
        {% for entry in not_being_added %}
            <tr>
                <td>{{ entry }}</td>
                <td>{% trans entry.get_state_display %}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock body %}

{% block scripts %}
    <script src="{% static 'ui/scripts/api_ajax.js' %}"></script>
    <script>
    </script>
{% endblock %}

ui/templates/ui/stages/add/NOT_STARTED.html
{% extends 'ui/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Manage Add Stage' %}{% endblock %}


{% block body %}
    <br>
    <a class="btn btn-primary" data-toggle="collapse" href="#add_form_collapse" role="button" aria-expanded="false"
       aria-controls="collapseExample">
        {% trans 'Add Entry To Competition Manually' %}
    </a>
    <a class="btn btn-primary" href="{% url 'ui/check_in' stage.competition.organisation.slug stage.competition.id %}">
        {% trans 'Open Check In' %}
    </a>
    <div class="collapse" id="add_form_collapse">
        <form id="manual_add_form" class="container">
            <div class="form-group row">
                <label for="manual_name" class="col-form-label">
                    {% trans 'Name:' %}
                </label>
                <input id="manual_name" type="text" class="form-control" required>
            </div>
            <div class="form-group row">
                <label for="manual_license" class="col-form-label">
                    {% trans 'Licence Number:' %}
                </label>
                <input id="manual_license" type="text" class="form-control" required>
            </div>
            <div class="form-group row">
                <label for="manual_club" class="col-form-label">
                    {% trans 'Club:' %}
                </label>
                <input id="manual_club" type="text" class="form-control" required>
            </div>
            <div class="form-group row">
                <div class="col form-check-inline">
                    <input id="check_in_automatically" type="checkbox" class="form-check-input">
                    <label for="check_in_automatically" class="form-check-label ">
                        {% trans 'Check in automatically' %}
                    </label>
                </div>
                <div class="col">
                    <button type="button" class="btn btn-success" onclick="submit_form()">{% trans "Add" %}</button>
                </div>
            </div>
        </form>
    </div>
    <br>
    <h2>{% trans "Un-Added Entries" %}</h2>
    <table class="table" id="entry_table">
        <tr>
            <th><input id="super_selector" type="checkbox" onchange="super_selector_change()"></th>
            <th>{% trans 'Seed' %}</th>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Status' %}</th>
        </tr>
        {% for entry in possible_additions %}
            <tr>
                <td><input type="checkbox" data-entry_id="{{ entry.id }}"></td>
                <td>{{ entry.seed }}</td>
                <td>{{ entry }}</td>
                <td>{% trans entry.get_state_display %}</td>
            </tr>
        {% endfor %}
    </table>
    <button type="button" class="btn btn-primary" id="add_selected">{% trans 'Add selected entries to competition flow' %}</button>
{% endblock body %}

{% block scripts %}
    <script src="{% static 'ui/scripts/api_ajax.js' %}"></script>
    <script>
        let form = $("#manual_add_form")[0];

        function submit_form() {
            if (!form.checkValidity()) {
                // Create the temporary button, click and remove it
                const tmpSubmit = document.createElement('button');
                form.appendChild(tmpSubmit);
                tmpSubmit.click();
                form.removeChild(tmpSubmit);
                return
            }
            let success = function (data) {
                location.reload();
            };
            let data = {
                'type': 'add_entry',
                'name': $("#manual_name").val(),
                'license_number': $("#manual_license").val(),
                'club_name': $("#manual_club").val(),
                'check_in': $("#check_in_automatically").prop('checked') ? 1 : 0
            };
            api_post('{% url 'main/competition_endpoint' stage.competition.id %}', data, success);
        }

        $("#manual_name").autocomplete({
            source: function (req, add) {
                $.getJSON("{% url 'main/organisation_endpoint' stage.competition.organisation.id %}?type=autocomplete_competitor", {'name': req.term}, function (data) {
                    add(data.competitors)
                })
            },
            minLength: 3,
            select: function (event, ui) {
                event.preventDefault();
                $("#manual_license").val(ui.item.license_number);
                $("#manual_club").val(ui.item.club_name);
                $("#manual_name").val(ui.item.name);
            }
        }).autocomplete("instance")._renderItem = function (ul, item) {
            return $("<li>")
                .append("<div>" + item.name + "</div>")
                .appendTo(ul);
        };

        $('#add_selected').click(function (){
            let id_dict = $("td > input:checked").map(function(){return this.dataset.entry_id});
            var ids = Object.keys(id_dict).map(function(key){
                return id_dict[key];
            });
            ids = ids.slice(0,-2);
            let success = function (data) {location.reload();};

            let data = {'type': 'add_entries',
                        'ids': ids};
            api_post('{% url 'main/stage_endpoint' stage.id %}', $.param(data, true), success);
        });

        function super_selector_change() {
            $("td > input[type='checkbox']").prop('checked', $("#super_selector").prop('checked'))
        }

    </script>
{% endblock %}

ui/templates/ui/stages/add/READY.html
{% extends 'ui/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Manage Add Stage' %}{% endblock %}


{% block body %}
    <a class="btn btn-primary" href="{% url 'ui/check_in' stage.competition.organisation.slug stage.competition.id %}">
        {% trans 'Open Check In' %}
    </a>
    <br>
    <h2>{% trans "Entries to add" %}</h2>
    <table class="table" id="entry_table">
        <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Status' %}</th>
        </tr>
        {% for entry in entries %}
            <tr>
                <td>{{ entry }}</td>
                <td>{% trans entry.get_state_display %}</td>
            </tr>
        {% endfor %}
    </table>
    <button type="button" class="btn btn-primary" id="confirm_add_btn">{% trans 'Confirm this addition' %}</button>
{% endblock body %}

{% block scripts %}
    <script src="{% static 'ui/scripts/api_ajax.js' %}"></script>
    <script>

        $('#confirm_add_btn').click(function (e) {
            let success = function (data) {
                location.assign('{% url 'ui/manage_competition' stage.competition.organisation.slug stage.competition.id %}');
            };
            let data = {
                'type': 'confirm_add'
            };
            api_post('{% url 'main/stage_endpoint' stage.id %}', data, success);
        });

    </script>
{% endblock %}